---
title: "Replicating the Simulations of Zou (2004)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Replicating the Simulations of Zou (2004)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ReplicateModifiedPoisson)
```

```{r scratch-work}
## Constant definitions ----------------------------------------------

probability_exposed <- 0.5
probability_stratum_1_given_exposed <- 0.6
probability_stratum_1_given_unexposed <- 0.4
risk_given_unexposed_stratum_2 <- 0.2


## Scratch -----------------------------------------------------------

data <- simulate_data(
  500,
  probability_exposed,
  probability_stratum_1_given_exposed,
  probability_stratum_1_given_unexposed,
  risk_given_unexposed_stratum_2,
  relative_risk_exposed = 2,
  relative_risk_stratum_1 = 1.5
)

run_mantel_haenszel(
  data$exposed,
  data$outcome,
  data$stratum
)

run_modified_poisson_glm(
  outcome ~ exposed + stratum, data = data, id = data$id
)

res <- glm(outcome ~ exposed + stratum, data = data)
confint(res)
suppressMessages(confint(res))

run_poisson_glm <- function(model_formula, data) {
  fit <- glm(model_formula, data = data, family = poisson)
  list(
    est = exp(coef(fit)[[2]]),
    ci = suppressMessages(exp(unname(confint(fit)[2, ])))
  )
}
run_poisson_glm(outcome ~ exposed + stratum, data = data)

run_log_binomial_glm(outcome ~ exposed + stratum, data = data)


x <- expand.grid(
  relative_risk_exposed = 1,
  n = c(100, 200, 500),
  relative_risk_stratum_1 = c(2, 3)
)[, c(1, 3, 2)]
x$x1 <- compute_risk(
  1, 1,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x2 <- compute_risk(
  0, 1,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x3 <- compute_risk(
  1, 2,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x4 <- compute_risk(
  0, 2,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)

x <- expand.grid(
  relative_risk_exposed = 2,
  n = c(100, 200, 500),
  relative_risk_stratum_1 = c(2, 1.5)
)[, c(1, 3, 2)]
x$x1 <- compute_risk(
  1, 1,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x2 <- compute_risk(
  0, 1,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x3 <- compute_risk(
  1, 2,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x4 <- compute_risk(
  0, 2,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)

x <- expand.grid(
  relative_risk_exposed = 3,
  n = c(100, 200, 500),
  relative_risk_stratum_1 = c(1.5, 1.25)
)[, c(1, 3, 2)]
x$x1 <- compute_risk(
  1, 1,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x2 <- compute_risk(
  0, 1,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x3 <- compute_risk(
  1, 2,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)
x$x4 <- compute_risk(
  0, 2,
  risk_given_unexposed_stratum_2,
  x$relative_risk_exposed,
  x$relative_risk_stratum_1
)

z <- run_simulation(500, 0.5, 0.6, 0.4, 0.2, 2, 1.5)

set.seed(123)

zz <- furrr::future_map(
  1:20,
  ~ run_simulation(
    100, 0.5, 0.6, 0.4, 0.2, 2, 1.5
  ),
  .options = furrr::furrr_options(seed = TRUE)
)

get_result_by_approach(zz, "ci", "poisson_glm")
get_result_by_approach(zz, "est", "log_binomial_glm")

report_relative_bias_risk_ratio(zz, 2)
report_coverage_risk_ratio(zz, 2)

```
